/* soapxiaofangProxy.h
   Generated by gSOAP 2.8.17r from webservice.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapxiaofangProxy_H
#define soapxiaofangProxy_H
#include "soapH.h"

class SOAP_CMAC xiaofangProxy : public soap
{ public:
	/// Endpoint URL of service 'xiaofangProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	xiaofangProxy();
	/// Construct from another engine state
	xiaofangProxy(const struct soap&);
	/// Constructor with endpoint URL
	xiaofangProxy(const char *url);
	/// Constructor with engine input+output mode control
	xiaofangProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	xiaofangProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	xiaofangProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~xiaofangProxy();
	/// Initializer used by constructors
	virtual	void xiaofangProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'Dispatch-Login' (returns error code or SOAP_OK)
	virtual	int Dispatch_Login(std::string username, std::string password, ns__Login_Response &response) { return this->Dispatch_Login(NULL, NULL, username, password, response); }
	virtual	int Dispatch_Login(const char *endpoint, const char *soap_action, std::string username, std::string password, ns__Login_Response &response);

	/// Web service operation 'Dispatch-Logout' (returns error code or SOAP_OK)
	virtual	int Dispatch_Logout(std::string name, struct ns__LogOutResponse *out) { return this->Dispatch_Logout(NULL, NULL, name, out); }
	virtual	int Dispatch_Logout(const char *endpoint, const char *soap_action, std::string name, struct ns__LogOutResponse *out);

	/// Web service operation 'Dispatch-Keepalive' (returns error code or SOAP_OK)
	virtual	int Dispatch_Keepalive(void *_, struct ns__Dispatch_Keepalive_Request_Response *out) { return this->Dispatch_Keepalive(NULL, NULL, _, out); }
	virtual	int Dispatch_Keepalive(const char *endpoint, const char *soap_action, void *_, struct ns__Dispatch_Keepalive_Request_Response *out);

	/// Web service operation 'Dispatch-Entity-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Entity_Request(ns__Entity id, ns__EntityData &response) { return this->Dispatch_Entity_Request(NULL, NULL, id, response); }
	virtual	int Dispatch_Entity_Request(const char *endpoint, const char *soap_action, ns__Entity id, ns__EntityData &response);

	/// Web service operation 'Dispatch-Entity-Nofitication' (returns error code or SOAP_OK)
	virtual	int Dispatch_Entity_Nofitication(void *_, ns__Entity_Nofitication_Response &response) { return this->Dispatch_Entity_Nofitication(NULL, NULL, _, response); }
	virtual	int Dispatch_Entity_Nofitication(const char *endpoint, const char *soap_action, void *_, ns__Entity_Nofitication_Response &response);

	/// Web service operation 'Dispatch-Entity-Status-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Entity_Status_Notification(void *_, ns__Entity_Status_Notification &response) { return this->Dispatch_Entity_Status_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Entity_Status_Notification(const char *endpoint, const char *soap_action, void *_, ns__Entity_Status_Notification &response);

	/// Web service operation 'Dispatch-Append-Group' (returns error code or SOAP_OK)
	virtual	int Dispatch_Append_Group(ns__Group group, ns__Group &response) { return this->Dispatch_Append_Group(NULL, NULL, group, response); }
	virtual	int Dispatch_Append_Group(const char *endpoint, const char *soap_action, ns__Group group, ns__Group &response);

	/// Web service operation 'Dispatch-Modify-Group' (returns error code or SOAP_OK)
	virtual	int Dispatch_Modify_Group(ns__Group group, ns__Group &response) { return this->Dispatch_Modify_Group(NULL, NULL, group, response); }
	virtual	int Dispatch_Modify_Group(const char *endpoint, const char *soap_action, ns__Group group, ns__Group &response);

	/// Web service operation 'Dispatch-Modify-Participants' (returns error code or SOAP_OK)
	virtual	int Dispatch_Modify_Participants(ns__Modify_Participant request, ns__Group &response) { return this->Dispatch_Modify_Participants(NULL, NULL, request, response); }
	virtual	int Dispatch_Modify_Participants(const char *endpoint, const char *soap_action, ns__Modify_Participant request, ns__Group &response);

	/// Web service operation 'Dispatch-Delete-Group' (returns error code or SOAP_OK)
	virtual	int Dispatch_Delete_Group(ns__Entity group_id, struct ns__Delete_Group_Response *out) { return this->Dispatch_Delete_Group(NULL, NULL, group_id, out); }
	virtual	int Dispatch_Delete_Group(const char *endpoint, const char *soap_action, ns__Entity group_id, struct ns__Delete_Group_Response *out);

	/// Web service operation 'Dispatch-Dispatch-Participants-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Dispatch_Participants_Notification(void *_, ns__Modify_Participant &response) { return this->Dispatch_Dispatch_Participants_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Dispatch_Participants_Notification(const char *endpoint, const char *soap_action, void *_, ns__Modify_Participant &response);

	/// Web service operation 'Dispatch-Join-Group-Request-Nofitication' (returns error code or SOAP_OK)
	virtual	int Dispatch_Join_Group_Request_Nofitication(void *_, ns__Join_Group_Request_Nofitication &response) { return this->Dispatch_Join_Group_Request_Nofitication(NULL, NULL, _, response); }
	virtual	int Dispatch_Join_Group_Request_Nofitication(const char *endpoint, const char *soap_action, void *_, ns__Join_Group_Request_Nofitication &response);

	/// Web service operation 'Dispatch-Participant-Status-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Participant_Status_Notification(void *_, ns__Participant_Status_Notification &response) { return this->Dispatch_Participant_Status_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Participant_Status_Notification(const char *endpoint, const char *soap_action, void *_, ns__Participant_Status_Notification &response);

	/// Web service operation 'Dispatch-Media-Message-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Media_Message_Request(ns__Entity id, unsigned long from_message_id, std::string from_time, unsigned long max_message_count, ns__Media_Message &response) { return this->Dispatch_Media_Message_Request(NULL, NULL, id, from_message_id, from_time, max_message_count, response); }
	virtual	int Dispatch_Media_Message_Request(const char *endpoint, const char *soap_action, ns__Entity id, unsigned long from_message_id, std::string from_time, unsigned long max_message_count, ns__Media_Message &response);

	/// Web service operation 'Dispatch-Media-Message-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Media_Message_Notification(void *_, ns__Media_Message_Notification &response) { return this->Dispatch_Media_Message_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Media_Message_Notification(const char *endpoint, const char *soap_action, void *_, ns__Media_Message_Notification &response);

	/// Web service operation 'Dispatch-Participant-Connect-Request-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Participant_Connect_Request_Notification(void *_, ns__Participant_Connect_Request_Notification &response) { return this->Dispatch_Participant_Connect_Request_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Participant_Connect_Request_Notification(const char *endpoint, const char *soap_action, void *_, ns__Participant_Connect_Request_Notification &response);

	/// Web service operation 'Dispatch-Participant-Speak-Request-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Participant_Speak_Request_Notification(void *_, ns__Participant_Connect_Request_Notification &response) { return this->Dispatch_Participant_Speak_Request_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Participant_Speak_Request_Notification(const char *endpoint, const char *soap_action, void *_, ns__Participant_Connect_Request_Notification &response);

	/// Web service operation 'Dispatch-Invite-Participant-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Invite_Participant_Request(ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Invite_Participant_Request_Response *out) { return this->Dispatch_Invite_Participant_Request(NULL, NULL, group_id, account_id, out); }
	virtual	int Dispatch_Invite_Participant_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Invite_Participant_Request_Response *out);

	/// Web service operation 'Dispatch-Drop-Participant-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Drop_Participant_Request(ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Drop_Participant_Request_Response *out) { return this->Dispatch_Drop_Participant_Request(NULL, NULL, group_id, account_id, out); }
	virtual	int Dispatch_Drop_Participant_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Drop_Participant_Request_Response *out);

	/// Web service operation 'Dispatch-Release-Participant-Token-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Release_Participant_Token_Request(ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Release_Participant_Token_Request_Response *out) { return this->Dispatch_Release_Participant_Token_Request(NULL, NULL, group_id, account_id, out); }
	virtual	int Dispatch_Release_Participant_Token_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Release_Participant_Token_Request_Response *out);

	/// Web service operation 'Dispatch-Appoint-Participant-Speak-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Appoint_Participant_Speak_Request(ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Appoint_Participant_Speak_Request_Response *out) { return this->Dispatch_Appoint_Participant_Speak_Request(NULL, NULL, group_id, account_id, out); }
	virtual	int Dispatch_Appoint_Participant_Speak_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Appoint_Participant_Speak_Request_Response *out);

	/// Web service operation 'Dispatch-Jion-Group-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Jion_Group_Request(ns__Entity group_id, struct ns__Dispatch_Jion_Group_Request_Response *out) { return this->Dispatch_Jion_Group_Request(NULL, NULL, group_id, out); }
	virtual	int Dispatch_Jion_Group_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, struct ns__Dispatch_Jion_Group_Request_Response *out);

	/// Web service operation 'Dispatch-Leave-Group-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Leave_Group_Request(ns__Entity group_id, struct ns__Dispatch_Leave_Group_Request_Response *out) { return this->Dispatch_Leave_Group_Request(NULL, NULL, group_id, out); }
	virtual	int Dispatch_Leave_Group_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, struct ns__Dispatch_Leave_Group_Request_Response *out);

	/// Web service operation 'Dispatch-Session-Status-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Session_Status_Notification(void *_, ns__Session_Status_Notification &response) { return this->Dispatch_Session_Status_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Session_Status_Notification(const char *endpoint, const char *soap_action, void *_, ns__Session_Status_Notification &response);

	/// Web service operation 'Dispatch-Send-Message-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Send_Message_Request(unsigned long id, ns__MediaMessage message, struct ns__Dispatch_Send_Message_Request_Response *out) { return this->Dispatch_Send_Message_Request(NULL, NULL, id, message, out); }
	virtual	int Dispatch_Send_Message_Request(const char *endpoint, const char *soap_action, unsigned long id, ns__MediaMessage message, struct ns__Dispatch_Send_Message_Request_Response *out);

	/// Web service operation 'Dispatch-Kick-Participant-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Kick_Participant_Request(ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Kick_Participant_Request_Response *out) { return this->Dispatch_Kick_Participant_Request(NULL, NULL, group_id, account_id, out); }
	virtual	int Dispatch_Kick_Participant_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, ns__Entity account_id, struct ns__Dispatch_Kick_Participant_Request_Response *out);

	/// Web service operation 'Dispatch-Start-Record-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Start_Record_Request(ns__Entity group_id, struct ns__Dispatch_Start_Record_Request_Response *out) { return this->Dispatch_Start_Record_Request(NULL, NULL, group_id, out); }
	virtual	int Dispatch_Start_Record_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, struct ns__Dispatch_Start_Record_Request_Response *out);

	/// Web service operation 'Dispatch-Stop-Record-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Stop_Record_Request(ns__Entity group_id, struct ns__Dispatch_Stop_Record_Request_Response *out) { return this->Dispatch_Stop_Record_Request(NULL, NULL, group_id, out); }
	virtual	int Dispatch_Stop_Record_Request(const char *endpoint, const char *soap_action, ns__Entity group_id, struct ns__Dispatch_Stop_Record_Request_Response *out);

	/// Web service operation 'Dispatch-Record-Status-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Record_Status_Notification(void *_, ns__Dispatch_Record_Status &response) { return this->Dispatch_Record_Status_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Record_Status_Notification(const char *endpoint, const char *soap_action, void *_, ns__Dispatch_Record_Status &response);

	/// Web service operation 'Dispatch-Subscribe-Account-Location-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Subscribe_Account_Location_Request(bool subscribing, ns__Entity account_id, unsigned long ttl, struct ns__Dispatch_Subscribe_Account_Location_Request_Response *out) { return this->Dispatch_Subscribe_Account_Location_Request(NULL, NULL, subscribing, account_id, ttl, out); }
	virtual	int Dispatch_Subscribe_Account_Location_Request(const char *endpoint, const char *soap_action, bool subscribing, ns__Entity account_id, unsigned long ttl, struct ns__Dispatch_Subscribe_Account_Location_Request_Response *out);

	/// Web service operation 'Dispatch-Account-Location-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Account_Location_Notification(void *_, ns__Dispatch_Account_Location_Notification_Response &response) { return this->Dispatch_Account_Location_Notification(NULL, NULL, _, response); }
	virtual	int Dispatch_Account_Location_Notification(const char *endpoint, const char *soap_action, void *_, ns__Dispatch_Account_Location_Notification_Response &response);

	/// Web service operation 'Dispatch-Append-Alert-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Append_Alert_Request(ns__Alert alert, std::list<ns__Account >acount, ns__Alert &response) { return this->Dispatch_Append_Alert_Request(NULL, NULL, alert, acount, response); }
	virtual	int Dispatch_Append_Alert_Request(const char *endpoint, const char *soap_action, ns__Alert alert, std::list<ns__Account >acount, ns__Alert &response);

	/// Web service operation 'Dispatch-Modify-Alert-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Modify_Alert_Request(ns__Alert alert, struct ns__Dispatch_Modify_Alert_Request_Response *out) { return this->Dispatch_Modify_Alert_Request(NULL, NULL, alert, out); }
	virtual	int Dispatch_Modify_Alert_Request(const char *endpoint, const char *soap_action, ns__Alert alert, struct ns__Dispatch_Modify_Alert_Request_Response *out);

	/// Web service operation 'Dispatch-Stop-Alert-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Stop_Alert_Request(ns__Entity alert_id, struct ns__Dispatch_Stop_Alert_Request_Response *out) { return this->Dispatch_Stop_Alert_Request(NULL, NULL, alert_id, out); }
	virtual	int Dispatch_Stop_Alert_Request(const char *endpoint, const char *soap_action, ns__Entity alert_id, struct ns__Dispatch_Stop_Alert_Request_Response *out);

	/// Web service operation 'Dispatch-Alert-Overed-Notification' (returns error code or SOAP_OK)
	virtual	int Dispatch_Alert_Overed_Notification(ns__Entity alert_id, struct ns__Dispatch_Alert_Overed_Notification_Response *out) { return this->Dispatch_Alert_Overed_Notification(NULL, NULL, alert_id, out); }
	virtual	int Dispatch_Alert_Overed_Notification(const char *endpoint, const char *soap_action, ns__Entity alert_id, struct ns__Dispatch_Alert_Overed_Notification_Response *out);

	/// Web service operation 'Dispatch-History-Alert-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_History_Alert_Request(std::string name, std::string create_time_from, std::string create_time_to, std::string alram_time_from, std::string alram_time_to, std::string over_time_from, std::string over_time_to, std::list<ns__HistoryAlert >&response) { return this->Dispatch_History_Alert_Request(NULL, NULL, name, create_time_from, create_time_to, alram_time_from, alram_time_to, over_time_from, over_time_to, response); }
	virtual	int Dispatch_History_Alert_Request(const char *endpoint, const char *soap_action, std::string name, std::string create_time_from, std::string create_time_to, std::string alram_time_from, std::string alram_time_to, std::string over_time_from, std::string over_time_to, std::list<ns__HistoryAlert >&response);

	/// Web service operation 'Dispatch-Alert-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Alert_Request(unsigned long alert_id, ns__Alert &response) { return this->Dispatch_Alert_Request(NULL, NULL, alert_id, response); }
	virtual	int Dispatch_Alert_Request(const char *endpoint, const char *soap_action, unsigned long alert_id, ns__Alert &response);

	/// Web service operation 'Dispatch-History-Alert-Message-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_History_Alert_Message_Request(unsigned long history_alert_id, unsigned long from_message_id, std::string from_time, unsigned long max_message_count, ns__Dispatch_History_Alert_Message &response) { return this->Dispatch_History_Alert_Message_Request(NULL, NULL, history_alert_id, from_message_id, from_time, max_message_count, response); }
	virtual	int Dispatch_History_Alert_Message_Request(const char *endpoint, const char *soap_action, unsigned long history_alert_id, unsigned long from_message_id, std::string from_time, unsigned long max_message_count, ns__Dispatch_History_Alert_Message &response);

	/// Web service operation 'Dispatch-Delete-History-Alert-Request' (returns error code or SOAP_OK)
	virtual	int Dispatch_Delete_History_Alert_Request(unsigned long history_alert_id, struct ns__Dispatch_Delete_History_Alert_Request_Response *out) { return this->Dispatch_Delete_History_Alert_Request(NULL, NULL, history_alert_id, out); }
	virtual	int Dispatch_Delete_History_Alert_Request(const char *endpoint, const char *soap_action, unsigned long history_alert_id, struct ns__Dispatch_Delete_History_Alert_Request_Response *out);
};
#endif
